[package]
name = "avian_smooth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avian3d = "0.1"
bevy = {version="0.14", features=["dynamic_linking"]}
bevy-inspector-egui = "0.25.1"
